name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_REPO }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_REPO }}
  push_to_psgallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to PowerShell Gallery
        run: docker run -v /home/runner/work/DFIR-O365RC/DFIR-O365RC:/mount_point mcr.microsoft.com/dotnet/sdk:8.0 pwsh -Command Publish-PSResource -Path "/mount_point/DFIR-O365RC" -Repository "PSGallery" -ApiKey "${{ secrets.PSGALLERY_TOKEN }}" -SkipModuleManifestValidate $true