name: Publish module to PowerShell Gallery

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_psgallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to PowerShell Gallery
        env:
          APIKEY: ${{ secrets.PSGALLERY_TOKEN }}
        run: ./.github/workflows/publish_psgallery.ps1
        shell: pwsh