name: Publish module to PowerShell Gallery

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_psgallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to PowerShell Gallery
        run: docker run -v /home/runner/work/DFIR-O365RC/DFIR-O365RC:/mount_point mcr.microsoft.com/dotnet/sdk:8.0 pwsh -Command Publish-PSResource -Path "/mount_point/DFIR-O365RC" -Repository "PSGallery" -ApiKey "${{ secrets.PSGALLERY_TOKEN }}" -SkipModuleManifestValidate $true